# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- task: TerraformCLI@0
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'azure(9909fced-8203-44b6-af68-11f833a37e60)'
    allowTelemetryCollection: true
- task: TerraformCLI@0
  inputs:
    command: 'plan'
    environmentServiceName: 'azure(9909fced-8203-44b6-af68-11f833a37e60)'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  inputs:
    command: 'apply'
    environmentServiceName: 'azure(9909fced-8203-44b6-af68-11f833a37e60)'
    runAzLogin: true
    allowTelemetryCollection: true
